# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-14 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_mzuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mzuser',
            old_name='u_roilid',
            new_name='u_roleid',
        ),
    ]
