# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-01 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_cart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='mzmarket_cart',
        ),
    ]
