# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-01 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20200301_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.MZUser'),
        ),
    ]
