# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-05 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20200301_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_server_ip', models.CharField(max_length=32)),
                ('s_server_port', models.CharField(max_length=32)),
                ('s_server_username', models.CharField(max_length=32)),
                ('s_server_password', models.CharField(max_length=64)),
            ],
        ),
    ]
