# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-05 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_server_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Server_info',
            new_name='ServerInfo',
        ),
    ]
