# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-06 04:44
from __future__ import unicode_literals

import App.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20200305_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_paymoney', models.FloatField(default=0)),
                ('o_create', models.DateTimeField(auto_now=True)),
                ('o_status', models.IntegerField(default=1)),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.MZUser')),
            ],
            options={
                'db_table': 'mz_order',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_goods', models.FloatField(verbose_name=App.models.Goods)),
                ('o_goods_num', models.IntegerField(default=1)),
                ('o_platformordernumber', models.CharField(max_length=255)),
                ('o_extdata', models.CharField(max_length=128)),
                ('o_realmoney', models.FloatField(default=0)),
                ('o_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Order')),
            ],
            options={
                'db_table': 'mz_ordergoods',
            },
        ),
    ]
