# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-06 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_order_ordergoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='o_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Goods'),
        ),
    ]
