# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-06 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20200306_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='mzuser',
            name='u_rolename',
            field=models.CharField(default='无', max_length=64),
        ),
    ]
